version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es-analyst-8-8
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana-analyst-8-8
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # Chave fixa de 32 caracteres para permitir criação de regras/alertas
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=e3f1a7c4b9d26e50a1c2d3e4f5a6b7c8
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
